version: "3.9"

services:
  redis:
    restart: always
    image: redis:7.0.8-alpine
    expose:
      - 6379

  web:
    restart: always
    build: .
    volumes:
      - .:/code
    command: python3 app.py
    container_name: social_media_task
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CACHE_TYPE=redis
      - CACHE_DEFAULT_TIMEOUT=500
    depends_on:
      - redis
